// src/components/react/PasswordInput.tsx
import { validationPW } from "@assets/ts/inputCheck";
import { useActiveElement } from "./module/activeElement";
import { useCallback, useContext, useRef, useEffect, useState, type ActionDispatch, useMemo } from "react";
import CheckSvg from "./SvgComponents/CheckSvg";
import Eye from "./Eye";
import anime from "animejs";
import { allCheck } from "./module/state";
import type { InputType } from "./module/type";

export default function PassWordInput({ mode, context }: {
    mode: "new" | "change" | "input", context: ActionDispatch<[target: {
        name: InputType;
        isValid: boolean;
    }]>
}) {

    const [critMsg, setCritMsg] = useState<(undefined | boolean)[]>(new Array(allCheck.length).fill(undefined))
    const [pwdValid, setPwdValid] = useState<boolean | undefined>(undefined)
    const [ifVisible, setIfVisible] = useState<boolean>(false)
    const [isUnfold, setIsUnfold] = useState<boolean>(false)
    const critDiv = useRef<HTMLDivElement | null>(null)
    const input = useRef<HTMLInputElement | null>(null)
    const wrapper = useRef<HTMLDivElement | null>(null)
    const dispatch = useContext(context)
    const active = useActiveElement()

    const animeFocus = (sens: "focus" | "blur") => {
        anime({
            targets: critDiv.current,
            duration: 400,
            height: sens == "focus" ? "120px" : "0px",
            easing: "easeOutSine",
        })
        setIsUnfold(sens == "focus");
    }

    const handleClick: React.MouseEventHandler<HTMLButtonElement> = useCallback((e) => {
        e.preventDefault()
        setIfVisible(!ifVisible)
    }, [ifVisible])

    const handleChange = useCallback((input: React.ChangeEvent) => {
        const valid = validationPW(allCheck, input.target.value);
        setPwdValid(input.target.value == "" ? undefined : !valid.disabled)
        setCritMsg(valid.test);
        if (dispatch) dispatch({ name: mode + "_password", isValid: valid.disabled })
    }, []);

    useEffect(() => {
        animeFocus(!wrapper.current?.contains(active ?? null) ? 'blur' : "focus")
    }, [active])

    return (
        <div ref={wrapper} className="flex flex-col w-full space-y-1.5">
            <div className={`flex overflow-hidden border rounded-xl relative ${isUnfold ? "outline-2 outline-solid outline-offset-0" : ""} ${pwdValid == undefined ? "border-zinc-600" : pwdValid ? "border-green-600 outline-green-600" : "border-red-600 outline-red-600"}`}>
                <input required ref={input} className="p-1.5 w-full placeholder:text-center" type={ifVisible ? "text" : "password"} name={mode == 'change' ? "newPassword" : "password"} placeholder={`${mode == "change" ? "Nouveau" : ""} Mot de passe`} onChange={handleChange}></input>
                <button className="absolute w-6 h-9  right-4 flex justify-center items-center" onClick={handleClick}>
                    <Eye etat={ifVisible} />
                </button>
            </div>
            <div ref={critDiv} className="overflow-hidden" style={{ height: "0px" }}>
                {
                    mode != "input" && allCheck.map((elem, i) => (
                        <div key={i} className="flex space-x-2">
                            <div className="w-4">
                                <CheckSvg check={critMsg[i]} />
                            </div>
                            <p className={`${critMsg[i] ? "text-green-600" : "text-slate-600"}`}>{elem.msg}</p>
                        </div>
                    ))
                }
            </div>
        </div>
    )
}

// src/components/svelte/PassWordInput.svelte
<script lang="ts">
    import anime from "animejs";
    import CheckSvg from "@svelte/SvgComponants/CheckSvg.svelte";
    import Eye from "./Eye.svelte";
    import { checkingAll, testList } from "@assets/ts/inputCheck";

    interface PassCheck {
        fn: Function;
        msg: string;
    }

    let {
        changeMode = false,
        boolPW = $bindable(false),
        greatPW = $bindable(""),
        Password = $bindable(""),
    }: {
        changeMode?: boolean;
        boolPW?: boolean;
        greatPW?: string;
        Password?: string;
    } = $props();

    let divCheck: HTMLDivElement;
    let allCheck: PassCheck[] = $state([
        { fn: testList.minL, msg: "Plus de 11 caractére" },
        { fn: testList.numCheck, msg: "Au moins un nombre" },
        { fn: testList.oneUpper, msg: "Au moins une Majuscule" },
        { fn: testList.oneLower, msg: "Au moins une Minuscule" },
        {
            fn: testList.specChar,
            msg: "Au moins un caractere special (#|~!?,.§€$£%:*())",
        },
    ]);

    let passwordInput: string = $state("");
    let outCheck: boolean[] = $state(Array(allCheck.length).fill(false));
    let checking = $derived(checkingAll([...outCheck], passwordInput));
    let outline: string = $derived.by(() => {
        switch (checking) {
            case "border-green-600 focus:outline-green-600":
                return "outline-green-600";
            case "border-red-600 focus:outline-red-600":
                return "outline-red-600";
        }
        return "outline-zinc-500";
    });

    let widthCheckDiv = $state(0);
    let heightCheckDiv: 120 | 82 = $derived(widthCheckDiv < 470 ? 120 : 82);

    let isVisible = $state(false);
    let isUnfold = $state(false);
    let wrapper: HTMLDivElement | null = $state(null);
    let activeElement: Element | null | undefined = $state(null);

    const folder = (sens: "fold" | "unfold") => {
        anime({
            targets: divCheck,
            height: sens == "unfold" ? `${heightCheckDiv}px` : `0px`,
            duration: 250,
            easing: "easeInQuad",
        });
        isUnfold = sens == "unfold";
    };

    const onclick = () => {
        isVisible = !isVisible;
        if (!isUnfold) folder("unfold");
    };

    const onfocus = () => {
        if (!isUnfold) folder("unfold");
    };

    const oninput = (
        e: Event & {
            currentTarget: EventTarget & HTMLInputElement;
        },
    ) => {
        passwordInput = e.currentTarget.value;
    };

    $effect(() => {
        if (!wrapper?.contains(activeElement ?? null)) {
            folder("fold");
        }
    });

    $effect(() => {
        greatPW = checking;
        boolPW = checking == "border-green-600 focus:outline-green-600";
        Password = passwordInput;
    });
</script>

<svelte:document bind:activeElement />
<div class="w-full" bind:this={wrapper}>
    <div
        style:outline-width={isUnfold ? "1px" : ""}
        style:outline-style={isUnfold ? "solid" : ""}
        class="{checking} {outline} relative flex rounded-xl overflow-hidden border"
    >
        <input
            {onfocus}
            {oninput}
            type={isVisible ? "text" : "password"}
            name="Password"
            class="py-1.5 pl-2 w-full focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-offset-0"
            placeholder={!changeMode ? "Mot de passe" : "Nouveau mot de passe"}
            required
        />
        <button
            {onclick}
            class="absolute justify-center items-center right-4 w-6 h-9"
        >
            <Eye etat={isVisible} />
        </button>
    </div>

    <div
        bind:this={divCheck}
        bind:clientWidth={widthCheckDiv}
        class="justify-start h-0 flex overflow-hidden"
    >
        <div
            class="flex flex-col flex-wrap ml-2 my-1"
            style:height={heightCheckDiv + "px"}
        >
            {#each allCheck as check, i}
                <div class="flex space-x-2">
                    <div class="w-4">
                        <CheckSvg
                            check={check.fn(passwordInput)}
                            bind:out={outCheck[i]}
                        />
                    </div>
                    <p
                        class={check.fn(passwordInput)
                            ? "text-green-600 "
                            : "text-slate-600"}
                    >
                        {@html check.msg}
                    </p>
                </div>
            {/each}
        </div>
    </div>
</div>
